CRUD/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls')),
    path('',include('authentication.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.homePage,name='home-page'),
    path('posts/',views.postPage,name='post-page'),
    path('create-post/',views.createPost,name='create-post'),
    path('update-post/<int:postid>',views.updatePost,name='update-post'),
    path('delete-post/<int:postid>',views.deletePost,name='delete-post'),
    path('detailed-post/<int:postid>',views.detailedPost,name='detailed-post'),
    path('comments/<str:postid>/',views.LoadComments,name='load-comments'),
    path('post-comment/<str:postid>/',views.PostComment,name='post-comment'),
    path('create-profile/',views.CreateUserProfile, name='create-profile'),
    path('update-profile/<int:profileid>/',views.EditUserProfile, name='update-profile'),
    path('like-post/<int:postid>/',views.likePost, name='like-post'),
    path('bookmark-post/<int:postid>/',views.bookMarkPost, name='bookmark-post'),
    path('post-status/<int:postid>/',views.statusCheck, name='post-status'),
    path('trending-posts/',views.top3Posts, name='top-3-posts'),
    path('view-profile/<int:profileid>/',views.UserProfileView, name='userprofile-view'),
    path('followers/<int:profileid>/',views.followUser, name='user-follow'),
    path('profile-status/<int:profileid>/',views.ProfileStatusCheck, name='profile-status'),
    path('pwd-change/',views.changePassword,name='change-password'),
    path('create-post/upload_image',views.UploadImage, name="upload-image"),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify
from tinymce.models import HTMLField

#Adding a natural key to User model, so it can be serialized as ForeignKey
def natural_key(self):
    return self.username

#Monkey_Patching
User.add_to_class("natural_key",natural_key)


class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE, related_name="profile_info")
    profileBackground=models.ImageField(upload_to='profile_images/',blank=True, default='defaultBackground.jpg')
    profileImg=models.ImageField(upload_to='profile_images/', blank=True, default='defaultUser.jpg')
    firstName=models.CharField(max_length=30, blank=False, null=False)
    lastName=models.CharField(max_length=30, blank=False, null=False)
    pronoun=models.CharField(max_length=15, blank=True, null=True)
    bio=HTMLField()
    location=models.CharField(max_length=50, blank=False, null=False) #state/ country
    doj=models.DateField(auto_now_add=True) #date of joining
    followers=models.ManyToManyField(User,related_name="following")
    instagram=models.URLField(max_length=150)
    x=models.URLField(max_length=150)
    github=models.URLField(max_length=150)
    telegram=models.URLField(max_length=150)

    def __str__(self) -> str:
        return self.firstName+" "+self.lastName

class GenreList(models.Model):
    name=models.CharField(max_length=40)
    slug=models.SlugField(max_length=50, blank=True)
    description=models.TextField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    
    def __str__(self) -> str:
        return self.name

class post(models.Model):
    title=models.CharField(max_length=100)
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    tags=models.ManyToManyField(GenreList)
    genre=models.CharField(max_length=150, null=True, blank=True)
    ratings=models.DecimalField(max_digits=3,decimal_places=2,null=True,blank=True)
    image=models.ImageField(upload_to='posts_images/',blank=True, default='defaultBackground.jpg')
    content=HTMLField()
    date_posted=models.DateTimeField(default=timezone.now)
    date_modified=models.DateTimeField(auto_now=True)
    likes=models.ManyToManyField(User, related_name='liked_post')
    bookmark=models.ManyToManyField(User, related_name='bookmarked_post')
    isDraft=models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.title}--{self.author}"

    class Meta:
       ordering=["-date_modified","-date_posted"] 

class comments(models.Model):
    post=models.ForeignKey(post,on_delete=models.CASCADE,related_name="comments")
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name="comments",null=True)
    body=models.CharField(max_length=200,blank=False)
    comment_posted=models.DateTimeField(auto_now_add=True)

    def str_comment_posted(self):
        return self.comment_posted.strftime("%b %d %y, %H:%M")

    def profile_pic_link(self):
        return self.user.profile_info.profileImg.url

    def __str__(self) -> str:
        return f"{self.user} --> {self.body[:11]}"

    class Meta:
        ordering=["-comment_posted",]

post/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .form import postForm, profileForm
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import reverse
from .models import post,comments,UserProfile
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count
from django.core.serializers.json import Serializer
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.forms import SetPasswordForm

from django.views.decorators.csrf import csrf_exempt
import os
from django.conf import settings
from uuid import uuid4


def homePage(request):
    return render(request,'post/homepage.html')


#enables user to upload images via tinyMCE editor for their post
@csrf_exempt
def UploadImage(request):
    if request.method != "POST":
        return JsonResponse({'message': "wrong request"})

    file_obj = request.FILES['file']
    print(file_obj)
    file_name_suffix = file_obj.name.split('.')[-1]

    if file_name_suffix not in ['jpeg','jpg','gif','png']:
        return JsonResponse({'message':f'wrong file suffix - {file_name_suffix}. It should be .jpg, .gif, .jpeg, .png'})

    file_path=os.path.join(settings.MEDIA_ROOT,'post_content_images',file_obj.name)

    if os.path.exists(file_path):
        file_obj.name=str(uuid4) + '.' + file_name_suffix

    with open(file_path, 'wb+') as f:
        for chunk in file_obj.chunks():
            f.write(chunk)

        return JsonResponse({'message': "image uploaded successfully!",
            'location': os.path.join(settings.MEDIA_URL,'post_content_images', file_obj.name)
        })

def UserProfileView(request, profileid):
    uprofile=UserProfile.objects.get(id=profileid)
    l_user=User.objects.get(id=uprofile.user.id)
    following=l_user.following.count()

    #User Stats
    post_liked=l_user.liked_post.count()
    post_commented=l_user.comments.count()
    post_bookmarked=l_user.bookmarked_post.count()
    likes_received=l_user.post_set.aggregate(tot_likes=Count('likes'))
    comments_received=l_user.post_set.aggregate(tot_comments=Count('comments'))
    followers=uprofile.followers.count()
    post_published=l_user.post_set.filter(isDraft=False).count()

    #getting bookmarks for that particular user
    bookmarks=l_user.bookmarked_post.all() if post_bookmarked>0 else "No Bookmarks Found 🤷🏻‍♂️"

    #getting drafted posts from the particular user
    drafted_posts=post.objects.filter(Q(author__id=l_user.id) & Q(isDraft=True)).order_by('-date_modified','-date_posted')
    draft_counts=drafted_posts.count()

    stats = {
        'post_liked': post_liked,
        'post_commented': post_commented,
        'post_bookmarked': post_bookmarked,
        'likes_received': likes_received['tot_likes'],
        'comments_received': comments_received['tot_comments'],
        'followers': followers,
        'post_published': post_published,
        'bookmarks': bookmarks,
        'draft_counts': draft_counts,
        'drafts': drafted_posts if draft_counts>0 else "No Drafts Found 🤷🏻‍♂️",
    }

    context={'user': uprofile, 'following': following, 'stats': stats}
    return render(request,'post/profileview.html',context)

def top3Posts(request):
    queryset=post.objects.annotate(nums_likes=Count('likes')).order_by('-nums_likes')[:3].values('id','title','nums_likes')
    return JsonResponse({'picks': list(queryset)},safe=False)

#like post
@login_required(login_url='login-page')
def likePost(request, postid):
    post_likes=get_object_or_404(post,id=postid)
    if request.user in post_likes.likes.all():
        liked=False
        post_likes.likes.remove(request.user)
    else:
        liked=True
        post_likes.likes.add(request.user)
    return JsonResponse({'liked':liked, 'like_count':post_likes.likes.count()})

#follow user
@login_required(login_url='login-page')
def followUser(request, profileid):
    lprofile=get_object_or_404(UserProfile,id=profileid)
    if request.user in lprofile.followers.all():
        followed=False
        lprofile.followers.remove(request.user)
    else:
        followed=True
        lprofile.followers.add(request.user)

    return JsonResponse({
        'followed':followed,
        'count': lprofile.followers.count(),
    })

#bookmark a post for future reference
@login_required(login_url='login-page')
def bookMarkPost(request, postid):
    post_bookmark=get_object_or_404(post,id=postid)
    if request.user in post_bookmark.bookmark.all():
        bookmarked=False
        post_bookmark.bookmark.remove(request.user)
    else:
        bookmarked=True
        post_bookmark.bookmark.add(request.user)
    return JsonResponse({'bookmarked':bookmarked,'bookmark_counts': post_bookmark.bookmark.count()})


#create profile for the user
@login_required(login_url='login-page')
def CreateUserProfile(request):
    if request.method == "POST":
        form=profileForm(request.POST, request.FILES)
        if form.is_valid():
            holder=form.save(commit=False)
            holder.user=request.user
            holder.save()
            return redirect('post-page')
    else:
        form=profileForm()
    context={'form':form}
    return render(request,"post/profileform.html",context)

#edit user profile
# @login_required(login_url='login-page')
def EditUserProfile(request,profileid):
    uprofile=UserProfile.objects.get(id=profileid)
    form=profileForm(instance=uprofile)
    if request.method=="POST":
        form=profileForm(request.POST,request.FILES,instance=uprofile)
        if form.is_valid():
            form.save() #saving it to DB
            return HttpResponseRedirect(reverse('post-page'))
    context={'form':form,'profile':uprofile, 'action': 'edit'}
    return render(request,'post/profileform.html',context)

#custom serializer for comment section
class CommentSerializer(Serializer):
    """custom serializer for comment section"""
    def end_object(self, obj):
        for field in self.selected_fields:
            if field == 'pk': continue
            elif field in self._current.keys(): continue
            else:
                try:
                    self._current[field]=getattr(obj,field)() #for model method
                    continue
                except TypeError: pass

                try:
                    self._current[field].getattr(obj,field) #for property method
                    continue
                except AttributeError: pass

        super(CommentSerializer, self).end_object(obj)

#Loads all the comments for a requested post
def LoadComments(request,postid):
    targetPost=post.objects.get(id=postid)

    # queryset=targetPost.comments.values('post','user','body','comment_posted','user__profile_info__profileImg')
    queryset=targetPost.comments.all()
    serializers=CommentSerializer()
    serialized_data=serializers.serialize(queryset,use_natural_foreign_keys=True,fields=['post','user','body','comment_posted','str_comment_posted','profile_pic_link'])

    return JsonResponse(serialized_data,safe=False,status=200)

#post the comment for the corresponding post
@login_required(login_url='login-page')
def PostComment(request,postid):
    if request.method=='POST':
        targetPost=post.objects.get(id=postid)
        text=request.POST.get('text')
        comment=comments.objects.create(post=targetPost,body=text,user=request.user)
        comment.save()
        return JsonResponse({'status':'success'})
    return JsonResponse({'status':'error'})

#read all posts
def postPage(request):
    cache=request.GET #copy get request in a placeholder

    #getting the query parameters
    psearch=cache.get('search') if cache.get('search') != None else ''
    pgenre=cache.get('genre') if cache.get('genre') != None else ''

    #query the db model
    if pgenre != '':
        posts=post.objects.filter(
            Q(isDraft=False) &
            Q(tags__name__icontains=pgenre)
        )
    else:
        posts=post.objects.filter(
            Q(isDraft=False) &
            (
                Q(author__username__icontains=psearch) |
                Q(title__icontains=psearch) |
                Q(content__icontains=psearch)
            )
        )

    user_check= True if User.objects.filter(id=request.user.id).exists() else False
    uprofile = following = None
    if user_check:
        l_user=User.objects.get(id=request.user.id)
        try:
            uprofile=UserProfile.objects.get(user=l_user)
            following=User.objects.get(id=uprofile.user.id).following.count()
        except:
            uprofile=None
            following=0

    context={'posts':posts, 'check':user_check, 'profile':uprofile, 'following':following}
    return render(request,'post/index.html',context)

#create post
@login_required(login_url='login-page')
def createPost(request):
    if request.method=="POST":
        form=postForm(request.POST,request.FILES)
        if form.is_valid():
            holder=form.save(commit=False)
            holder.author=request.user
            name=form.cleaned_data['title']
            print("{} is created.".format(name))
            holder.save()
            return HttpResponseRedirect(reverse('post-page'))
    else:
        form=postForm()
    context={'form':form}
    return render(request,'post/postcreateform.html',context)

#update post
@login_required(login_url='login-page')
def updatePost(request,postid):
    try:
        upost=post.objects.get(id=postid)
    except:
        raise "Requested post not found!!"
    form=''
    if request.user == upost.author:
        form=postForm(instance=upost)
        if request.method=="POST":
            form=postForm(request.POST,request.FILES,instance=upost)
            if form.is_valid():
                form.save() #saving it to DB
                name=form.cleaned_data["title"]
                print("{} has been updated successfully!!".format(name))
                return HttpResponseRedirect(reverse('post-page'))
    else:

post/templates/post/comment-section.html
<section class="comment-section" id="target-view">
  {% if request.user.is_authenticated %}
  <div class="post-comment container">
    <form action="" method="post" id="post-comment">
      {% csrf_token %}
      <input
        type="text"
        name="comment-text"
        id="comment-text"
        placeholder="enter ur comment..."
      />
      <button type="submit" class="comment-btn">
        <i class="fa-solid fa-arrow-right fa-2xl"></i>
      </button>
    </form>
  </div>
  {% endif %}
  <div class="load-comments container"></div>
</section>

post/templates/post/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Honk&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Anime OTAKU ⚡</title>
</head>
<body>
    <div id="home-bg">
        <nav class="home-nav">
            <p class="home-logo">Anime OTAKU</p>
            <ul>
                <li><a href="{% url 'post-page' %}">Posts</a></li>
                <li><a href="#">About</a></li>
                {% if request.user.is_authenticated %}
                <button><a href="{% url 'post-page' %}">Sign In</a></button>
                {% else %}
                <button><a href="{% url 'login-page' %}">Sign In</a></button>
                {% endif %}
            </ul>
        </nav>
        <div class="home-content">
            <h1>Become an Anime OTAKU!</h1>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. nesciunt tenetur vitae. Facere ut doloremque eveniet fuga quas!
            </p>
            <button><a href="{% url 'post-page' %}">Wanna Dive</a> <i class="fa-solid fa-arrow-right fa-beat"></i></button>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.net.min.js"></script>
    <script>
    VANTA.NET({
    el: "#home-bg",
    mouseControls: true,
    touchControls: true,
    gyroControls: false,
    minHeight: 200.00,
    minWidth: 200.00,
    scale: 1.00,
    scaleMobile: 1.00
    })
    </script>
</body>
</html>

post/templates/post/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jost&family=Outfit:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Honk&display=swap" rel="stylesheet">
    <title>Anime OTAKU ⚡</title>
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
    <script type="text/javascript" src="{% static 'js/script.js' %}" defer ></script>
</head>
<body>
    <div class="container">
        {% include "post/navbar.html" %}
        {% include "post/main.html" %}
        {% include "post/sidebar.html" %}
    </div>
</body>
</html>

post/templates/post/main.html
{% load static %}

<div class="main">

    <div class="notification-messages">
        {% if not request.user.is_authenticated and not profile %}
        <div class="pop-up-notifications">
            <p class="notification-text"><i class="notification-check fa-solid fa-bell fa-xl" style="color: #d2a80f;"></i> Profile creation is <b>still pending</b>, please rightaway!</p>
            <i class="notification-close fa-solid fa-xmark fa-xl"></i>
        </div>
        {% endif %}
        {% if messages %}
        {% for message in messages %}
        <div class="pop-up-notifications">
            <p class="notification-text"><i class="notification-check fa-solid fa-bell fa-xl" style="color: #d2a80f;"></i> {{ message }}</p>
            <i class="notification-close fa-solid fa-xmark fa-xl"></i>
        </div>
        {% endfor %}
        {% endif %}
    </div>

    {% if request.user.is_authenticated %}
    <div class="post-create">
        <button type="submit"><a href="{% url 'create-post' %}"><i class="fa-solid fa-square-plus"></i> CREATE</a></button>
    </div>
    {% endif%}
    {% for post in posts %}
    <div class="card {% cycle 'color1' 'color2' 'color3' %}">
        <a style="color:#333; text-decoration: none;" href="{% url 'userprofile-view' post.author.profile_info.id %}">
            <div class="author-info grid">
                <img class="post-user-pic" src="{{ post.author.profile_info.profileImg.url }}" alt="user-pic">
                <div class="info-container">
                    <div class="author"><small>{{ post.author }}</small></div>
                    <div class="date-posted"><small>{{ post.date_posted | date:"M j,y" }}</small></div>
                </div>
            </div>
        </a>
        <h1 class="title">{{ post.title }}</h1>
        <ul style="display: flex; flex-direction: row; align-items: center; justify-content: flex-start; gap: 20px;">
        {% for tag in post.tags.all %}
            <li class="color">#{{ tag }}</li>
        {% endfor %}
        </ul>
        <div class="flex" style="flex-direction: row; align-items: center; justify-content: flex-start; gap: 40px;">
            <div class="post-details flex">
                <p class="genre" style="color: #808080;"><i class="fa-regular fa-heart"></i> {{ post.likes.count }}</p>
                <p class="genre" style="color: #808080;"><i class="fa-regular fa-comment"></i> {{post.comments.count }}</p>
            </div>
            <button style="margin-right: 100px;" class="read-more" type="submit"><a href="{% url 'detailed-post' post.id %}">Read More <i class="fa-solid fa-arrow-right"></i></a></button>
        </div>
    </div>
    {% endfor %}
</div>

post/templates/post/navbar.html
{% load static %}

<div class="navbar">
    <a href="{% url 'home-page' %}"><h2 class="header">Anime OTAKU</h2></a>
    <div class="nav">
        <form class="search" action="" method='GET'>
            <button type="submit"><i class="fa-solid fa-magnifying-glass fa-xl"></i></button>
            <input type="text" name="search" id="searchbar" placeholder="search for posts...">
        </form>
        {% if check and request.user.is_authenticated %}
            {% if not profile %}
                <img id="nav-user-pic" src="{% static 'img/signup.png' %}" alt="user-pic">
            {% else %}
                <img id="nav-user-pic" src="{{ profile.profileImg.url }}" alt="user-pic">
            {% endif %}

        {% else %}
            <button class="login"><a href="{% url 'login-page' %}">Login</a></button>
        {% endif %}
    </div>
    {% if check and request.user.is_authenticated %}
        <div class="sub-menu-wrap" id="subMenu">
            <div class="sub-menu">
                {% if not profile %}
                <a href="{% url 'create-profile' %}" class="sub-menu-link">
                    <i class="dd-icon fa-solid fa-user"></i>
                    <p>Create Profile</p>
                    <span><i class="dd-arrow fa-solid fa-angle-down fa-rotate-270"></i></span>
                </a>
                {% else %}
                <div class="user-info"></div>
                    <img src="{{ profile.profileImg.url }}" alt="user pic">
                    <h4>{{ profile.firstName }} {{ profile.lastName }}</h4>
                </div>
                <hr>
                <a href="{% url 'userprofile-view' profile.id %}" class="sub-menu-link">
                    <i class="dd-icon fa-solid fa-user"></i>
                    <p>View Profile</p>
                    <span><i class="dd-arrow fa-solid fa-angle-down fa-rotate-270"></i></span>
                </a>
                {% endif %}

                <a href="#" class="sub-menu-link">
                    <i class="dd-icon fa-solid fa-gear"></i>
                    <p>Settings & Privacy</p>
                    <span><i class="dd-arrow fa-solid fa-angle-down fa-rotate-270"></i></span>
                </a>
                <a href="#" class="sub-menu-link">
                    <i class="dd-icon fa-solid fa-circle-info"></i>
                    <p>Help & Support</p>
                    <span><i class="dd-arrow fa-solid fa-angle-down fa-rotate-270"></i></span>
                </a>
                <a href="{% url 'logout-page' %}" class="sub-menu-link">
                    <i class="dd-icon fa-solid fa-right-from-bracket"></i>
                    <p>Logout</p>
                    <span><i class="dd-arrow fa-solid fa-angle-down fa-rotate-270"></i></span>
                </a>
            </div>
        </div>
    {% endif %}
</div>

post/templates/post/postcreateform.html
{% load static %}
{% load crispy_forms_tags %}
{% load specfuncs %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jost&family=Outfit:wght@300&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/post.css' %}">
    <script defer src="{% static 'js/post.js' %}"></script>
    <title>Create Post</title>
</head>
<body>
    <div class="container">
        {% if action == "edit" %}
            <h3 class="mt-4 mb-4 fw-bold">Edit Post</h3>
        {% else %}    
            <h3 class="mt-4 mb-4 fw-bold">Create Post</h3>
        {% endif %}    
        <form class="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            <div class="post-pic-container">
                {{form.image}}
                <label for="post-pic-input" class="post-pic">
                    {% if post.image.url %}
                        <img id="preview" src="{{ post.image.url }}" alt="post picture">
                    {% else %}
                        <img id="preview" src="https://images.unsplash.com/photo-1564944062924-57874442ddea?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="post picture">
                    {% endif %}
                    <span>Upload cover pic</span>
                </label>
            </div>
            <div class="post-title mb-4 mt-4">
                {{form.title}}
            </div>
            {{ form.isDraft|as_crispy_field }}
            {{form.tags|as_crispy_field}}
            {{form.content|as_crispy_field}}
            <button type="submit" class="mb-4 btn btn-success">Submit</button>
            <a href="{% url 'post-page' %}" class='mb-4 btn btn-danger'>Cancel</a>   
        </form>
    </div>

    <script>
        $(document).ready(function() {
            $('#id_tags').select2();
        });
        console.log('{{ post.image.url }}');
    </script>

</body>
</html>